import Head from "next/head";
import { NextPage } from "next";
import Banner from "../Components/HomeSections/Banner";
import TimerSection from "../Components/HomeSections/TimerSection";
import VStack from "../Components/Basic/VStack/VStack";
import EventInfo from "../Components/HomeSections/EventInfo";
import DirectionSection from "../Components/HomeSections/DirectionSection";
import GallerySection from "../Components/HomeSections/GallerySection";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <VStack className="gap-[2rem]">
        <Banner />
        <TimerSection />
        <EventInfo />
        <DirectionSection />
        <GallerySection />
      </VStack>
    </div>
  );
};

export default Home;
